### ISSUE TITLE
serializing object 

### ISSUE THREAD

**Issue by idanbar134** [path/android-priority-jobqueue#105]
Hello,

I get this message while trying to send an message with my application.
any idea what it can be?

3-29 17:50:37.733  19460-20234/com.nuro D/JOBS﹕ added job id: 15 class: PostMessage priority: 1 delay: 0 group : null persistent: true requires network: true
03-29 17:50:37.740  19460-20234/com.nuro D/JOBS﹕ pool-2-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 0). consumer thread: false
03-29 17:52:18.545  19460-20236/com.nuro D/JOBS﹕ Thread-16082: load factor check. true = (0 < 1)|| (0 * 3 < 0 + 0). consumer thread: true
03-29 17:52:18.546  19460-20236/com.nuro D/JOBS﹕ didn't allow me to die, re-running Thread-16082
03-29 17:52:18.547  19460-20236/com.nuro D/JOBS﹕ re-running consumer Thread-16082
03-29 17:52:19.294  19460-20234/com.nuro E/JOBS﹕ error while serializing object PostMessage
    java.io.NotSerializableException: com.nuro.Activities.ChatActivity
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
            at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
            at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
            at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
            at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
            at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue$JavaSerializer.serialize(SqliteJobQueue.java:347)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.safeSerialize(SqliteJobQueue.java:324)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.getSerializeBaseJob(SqliteJobQueue.java:319)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.bindValues(SqliteJobQueue.java:75)
            at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:59)
            at com.path.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:26)
            at com.path.android.jobqueue.JobManager.addJob(JobManager.java:499)
            at com.path.android.jobqueue.JobManager$4.run(JobManager.java:565)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
            at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
03-29 17:52:19.303  19460-20234/com.nuro D/JOBS﹕ added job id: 16 class: PostMessage priority: 1 delay: 0 group : null persistent: true requires network: true
03-29 17:52:19.309  19460-20234/com.nuro D/JOBS﹕ pool-2-thread-1: load factor check. false = (1 < 1)|| (1 * 3 < 0 + 0). consumer thread: false

**Comment by mecid** [comment]
Please show the job class code

**Comment by idanbar134** [comment]
Hi,

here:
http://pastebin.com/eW9y3zey

Best regards
Idan

On Sun, Mar 29, 2015 at 10:01 PM, Mecid <notifications@github.com> wrote:

> Please show the job class code
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/path/android-priority-jobqueue/issues/105#issuecomment-87455416>
> .
>



-- 
Idan Ayalon

**Comment by mecid** [comment]
You must use transient keyword for all fields which can't serialize like Activity or EditText

**Comment by idanbar134** [comment]
Thanks, I fixed it yesterday that way)
