### ISSUE TITLE
IllegalStateException : Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [path/android-priority-jobqueue#95]
I got this weird exception, which I can't even find its cause because the library got obfuscated:

java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
       at android.database.CursorWindow.nativeGetLong(CursorWindow.java)
       at android.database.CursorWindow.getLong(CursorWindow.java:511)
       at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:75)
       at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:220)
       at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
       at com.path.android.jobqueue.h.a.d.b(SqliteJobQueue.java:201)
       at com.path.android.jobqueue.a.a.b(CachedJobQueue.java:68)
       at com.path.android.jobqueue.f.d(JobManager.java:273)
       at com.path.android.jobqueue.f.c(JobManager.java:25)
       at com.path.android.jobqueue.h.a(JobManager.java:412)
       at com.path.android.jobqueue.d.a$b.run(JobConsumerExecutor.java:198)
       at java.lang.Thread.run(Thread.java:841)

Any way to find why it occurs, and how to fix it?

**Comment by LOG-TAG** [comment]
https://github.com/path/android-priority-jobqueue/issues/55

**Comment by AndroidDeveloperLB** [comment]
I don't see this exception there. Are you sure it can be it?

**Comment by yigit** [comment]
Hmm, weird. Is this something you can reproduce?

Also, there is no reason to obfuscate the library since it is open source anyways. You can also resolve it using the obfuscation output of proguard.

**Comment by yigit** [comment]
This issue was moved to yigit/android-priority-jobqueue#2

**Comment by AndroidDeveloperLB** [comment]
Can you please put on the main screen of this project, a link to the new one (the link you wrote here) ? 
It's just that searching "jobqueue" on Google always shows a link to this repo, and not the new one...
